### PR TITLE
Created an AxisButton class to monitor trigger buttons and schedule commands

### PR DESCRIPTION
**Pull request by jmullins16**
This still needs some work done to finish and implement our desired button layout!

- STILL NEEDS THE CORRECT THRESHOLD SET AFTER TESTING ON XBOX CONTROLLER
- USES IntakeDeploy() COMMAND ONLY AS AN EXAMPLE
- NEEDS TO HAVE COMMANDS RE-ARRANGED TO USE TRIGGERS INSTEAD OF BUMPERS

### CODE REVIEW

**Comment by jmullins16** [comment]
Completely agree on threshold. In my deep dive on this, there are some documented quirks with triggers that indicate the trigger reading starts at 0 (unpressed), and then when pressed immediately goes into the range from -1.0 to 1.0. I don't know if it's true or not, but I could not test last night. So that's one of the action items.

**Comment by jmullins16** [comment]
More on this PR since commits are accumulating.
- Added Grogu characterization project file and data
- Added talonvalid checks for some of the newer calls for current limiting, etc., because it was spamming the console on the benchtop board and impossible for Savannah to use for testing.

**Comment by jmullins16** [comment]
And more info on the game controllers after testing what WPILib can detect for triggers. (down the "rabbit hole")
- Legacy XBox One controllers only output 0 or 1 when a trigger was depressed (not a continuous range) when reading the Trigger axes
- Newer XBox controllers DO put out a continuous range as the button is depressed and the range starts at 0.0 and goes up to 1.0. 
- Any threshold between 0.0 and 1.0 will work for either legacy or newer styles, but newer controllers will be able to detect how far the trigger button has been depressed.
- Our threshold is presently half of the trigger press distance right now.
- The XBox elite controllers (driver controller) have a switch on the back which can change it between legacy and newer mode.
So the new class should work fine now that we know what the expected ranges are, and we can decide on a threshold to use.

**Review by ashanawaz — APPROVED** [review]
Looks good

**Pull request merged**
