### PR TITLE
Created initial floor conveyor code for Grogu

### PR DESCRIPTION
**Pull request by cgjyang**

### CODE REVIEW

**Review by ngupta-22 — COMMENTED** [review]
This looks good! Quick question though, why did you include the XboxController class in the FloorConveyor.h file? Is that for the conveyorDir_e variable?

**Comment by cgjyang** [comment]
> This looks good! Quick question though, why did you include the XboxController class in the FloorConveyor.h file? Is that for the conveyorDir_e variable?

Good point, it's not for the conveyorDir_e variable or necessary at all in the FloorConveyor.h file, so I'll make sure to delete it in a future PR

**Comment by jmullins16** [comment]
The floor conveyor (and vertical conveyor) will likely be commanded to "do something" as a sequence of commands until later told to "turn off", it should not stop the motors in the End method (and it should always be IsFinished=true). Otherise, when this is made part of an autonomous sequence, the command will turn on/off motors and they will not stay running during the auton sequence.

**Review by cgjyang — COMMENTED** [review]
I think I fixed everything that was mentioned in the comments, but lmk if I should change anything!

**Review by jmullins16 — APPROVED** [review]
Looks correct now

**Review by ngupta-22 — APPROVED** [review]
Looks good!

**Review by sfujimoto22 — APPROVED** [review]
We did a group review

**Review by ngupta-22 — APPROVED** [review]
Did a group review. It looks good!

**Pull request merged**
