### PR TITLE
Fixed Shooting Action and Intaking Action parallel commands

### PR DESCRIPTION
**Pull request by cgjyang**

### CODE REVIEW

**Review by ngupta-22 — APPROVED** [review]
Looks great!

**Review by sfujimoto22 — APPROVED** [review]
Looks good!

**Review by jmullins16 — COMMENTED** [review]
A few questons/changes:
- IntakingStop probably doesn't need to call IntakeDeploy (and the .h file can be removed)
- ShootingAction should not be stopping the Floor or Vertical conveyors (they should run toward shooter)
- ShootingStop should not be referencing the IntakeDeploy (and the .h file can be removed)

**Review by jmullins16 — APPROVED** [review]
Looks much better. Although the key change in observable functionality is that the the shooter will actually receive power cells when ShootingAction is called (just pointing out that the headline didn't say that). 👍 Good to go.

**Pull request merged**
