### PR TITLE
Added flashlightOn to ShooterRun command, and fixed instances through…

### PR DESCRIPTION
**Pull request by ashanawaz**
…out code.

### CODE REVIEW

**Review by cgjyang — APPROVED** [review]
Looks ready to go! Was also tested successfully with the PCM today

**Review by jmullins16 — APPROVED** [review]
I think we missed a pretty key concept here. ShooterRun was designed to only control the shooter/feeder wheels in the shooter subsystem. This did  not need to change at all. A second simple command (one that has Init/Execute/IsFinished/End) already existing in ShooterAim that was supposed to control the flashlight. Then group commands could all them both. Making ShooterRun handle everything actually limits things more than needed. Since this works, let's use it for the weekend, but then let's talk about the subsystem and command layers a little more to call out the different building blocks and maybe improve our naming.

**Review by jmullins16 — COMMENTED** [review]
I will add that this code in ShooterRun:
`    spdlog::info("ShooterRun - Init {}", m_shooterState);
    m_shooter->SetShooterSpeed(m_shooterState);
    RobotContainer *robotContainer = RobotContainer::GetInstance();
    robotContainer->m_shooter.FlashlightOn(m_lightOn);`
does the following:
1) does a spdlog call
2) uses the shooter subsystem (m_shooter) to set the speed
3) uses robotcontainer to get locate the shooter subsystem (which it already has)
4) uses the shooter subsystem from that to turn the flashlight on
It should just use m_shooter again to turn on the flashlight (no robotcontainer->GetInstance)

**Review by ngupta-22 — APPROVED** [review]
Looks good!

**Pull request merged**
